modLoader = "javafml"
loaderVersion = "[${forge_version_major},)"
license = "LGPL-3.0-only"

[[mods]]
 modId = "starlight"
 version = "${version}"
 displayName = "Starlight X Create"
 authors = "Spottedleaf & SirOMGitsYOU"
 description = '''
    Rewrites the light engine to fix lighting performance and lighting errors & Added Compatibility originally by AeiouEnigma ported to 1.18 by SirOMGitsYOU 
 '''
 logoFile = "logo.png"
 displayURL = "https://www.curseforge.com/minecraft/mc-mods/starlight-x-create"

 [[dependencies.starlight]]
  modId = "forge"
  mandatory = true
  versionRange = "[39.0.0,)"
  ordering = "NONE"
  side = "BOTH"

[[dependencies.starlight]]
  modId = "minecraft"
  mandatory = true
  versionRange = "[1.18, 1.19)"
  ordering = "NONE"
  side = "BOTH"